using System.Text;

namespace EA17LinkMLExporter;

internal static class PlantUmlWriter
{
    public static string Write(ModelSnapshot model)
    {
        var aliases = model.Classes.Select((item, index) => (item.Id, Alias: $"C{index + 1:D3}"))
            .Concat(model.Enums.Select((item, index) => (item.Id, Alias: $"E{index + 1:D3}")))
            .ToDictionary(x => x.Id, x => x.Alias);
        var classesByName = model.Classes.ToDictionary(x => x.Name, StringComparer.OrdinalIgnoreCase);
        var b = new StringBuilder();
        b.AppendLine("@startuml");
        b.AppendLine("' Generated by EA Semantic Model Toolkit. Unknown datatypes are display labels, not render errors.");
        b.AppendLine("!pragma layout smetana");
        b.AppendLine("top to bottom direction");
        b.AppendLine("hide methods");
        b.AppendLine("hide stereotypes");
        b.AppendLine("skinparam shadowing false");
        b.AppendLine("skinparam classAttributeIconSize 0");
        b.AppendLine("skinparam classBackgroundColor #FFF8F2");
        b.AppendLine("skinparam classBorderColor #8C7568");
        b.AppendLine("skinparam classArrowColor #5B6B8C");
        b.AppendLine("skinparam classFontColor #1F2937");
        b.AppendLine("skinparam linetype polyline").AppendLine();

        foreach (var cls in model.Classes.OrderBy(x => x.Name))
        {
            string declaration = cls.Abstract ? "abstract class" : "class";
            b.AppendLine($"{declaration} \"{Quoted(cls.Name)}\" as {aliases[cls.Id]} {{");
            foreach (var property in cls.Properties)
                b.AppendLine($"  + {Member(property.Name)}: {Member(TypeLabel(property.Type))} [{Multiplicity(property.Lower, property.Upper)}]");
            b.AppendLine("}");
        }
        foreach (var item in model.Enums.OrderBy(x => x.Name))
        {
            b.AppendLine($"enum \"{Quoted(item.Name)}\" as {aliases[item.Id]} {{");
            foreach (string value in item.Values) b.AppendLine("  " + Member(value));
            b.AppendLine("}");
        }

        b.AppendLine();
        foreach (var cls in model.Classes)
        foreach (string parentName in cls.Parents)
        {
            if (classesByName.TryGetValue(parentName, out var parent))
                b.AppendLine($"{aliases[parent.Id]} <|-- {aliases[cls.Id]}");
        }
        foreach (var relation in model.Relations)
        {
            if (!aliases.TryGetValue(relation.SourceId, out string? source) ||
                !aliases.TryGetValue(relation.TargetId, out string? target)) continue;
            string arrow = relation.Composition ? "*--" : "-->";
            string role = relation.TargetRole.Length > 0 ? relation.TargetRole : relation.SourceRole;
            string label = role.Length > 0 ? " : " + Member(role) : "";
            b.AppendLine($"{source} \"{Cardinality(relation.SourceMultiplicity)}\" {arrow} " +
                         $"\"{Cardinality(relation.TargetMultiplicity)}\" {target}{label}");
        }
        b.AppendLine().AppendLine("@enduml");
        return b.ToString();
    }

    private static string TypeLabel(string? value) => string.IsNullOrWhiteSpace(value) ? "unnamed" : value.Trim();
    private static string Multiplicity(string? lower, string? upper)
    {
        lower = string.IsNullOrWhiteSpace(lower) ? "0" : lower.Trim();
        upper = string.IsNullOrWhiteSpace(upper) ? "1" : upper.Trim();
        return lower == upper ? lower : lower + ".." + upper;
    }
    private static string Cardinality(string? value) => string.IsNullOrWhiteSpace(value) ? "0..1" : Member(value);
    private static string Quoted(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"")
        .Replace("\r", " ").Replace("\n", " ");
    private static string Member(string value) => value.Replace("\r", " ").Replace("\n", " ")
        .Replace("{", "(").Replace("}", ")").Replace("\"", "'").Trim();
}
